Update multidict requirement to >=4.5
multidict 4.4 causes the following error in `aiohttp`
headers: Optional[MultiMapping[str]]=None
TypeError: 'ABCMeta' object is not subscriptable